variables:
  GIT_DEPTH: 5

image: alpine:3.11

before_script:
  - apk add --no-cache subversion nodejs npm
  - npm i -g minify@5.1.1
  - svn co -q https://plugins.svn.wordpress.org/leaflet-map /repo
  - rm -rf /repo/trunk/*
  - cp -r * /repo/trunk
  - cd /repo

new version:
  stage: deploy
  script:
    # minify js
    - cd trunk/scripts
    - rm -f *.min.js
    - |
      for file in *.js; do 
      minify $file > $(basename $file .js).min.js; 
      done
    - cd /repo
    # add all svn
    - svn add --force .
    # new tag
    - svn cp trunk tags/${CI_COMMIT_TAG//v}
    - svn ci -m "${CI_COMMIT_MESSAGE}" --username $USER --password $PASSWORD
  rules:
    - if: $CI_COMMIT_TAG

update latest:
  stage: deploy
  script:
    # minify js
    - cd trunk/scripts
    - rm -f *.min.js
    - |
      for file in *.js; do 
      minify $file > $(basename $file .js).min.js; 
      done
    - cd /repo
    # add all svn
    - svn add --force .
    - svn ci -m "${CI_COMMIT_MESSAGE}" --username $USER --password $PASSWORD
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'