variables:
  GIT_DEPTH: 5

image: alpine

before_script:
  - apk add --no-cache subversion nodejs npm
  - npm i -g minify@5.1.1
  - svn co -q https://plugins.svn.wordpress.org/leaflet-map /repo
  - rm -rf /repo/trunk/*
  - cp -r * /repo/trunk
  - cd /repo

new version:
  stage: deploy
  script:
    # minify js
    - cd trunk/scripts
    - rm -f *.min.js
    - |
      for file in *.js; do 
      minify $file > $(basename $file .js).min.js; 
      done
    - cd /repo
    # tag and commit to svn
    - svn add --force .
    - svn cp trunk tags/${CI_COMMIT_TAG//v}
    - svn ci -m "${CI_COMMIT_MESSAGE}" --username $USER --password $PASSWORD
  only:
    - tags
