version: '3.3'

services:
  mysql:
    image: mariadb:10.5.8
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass

  cli:
    image: bozdoz/wordpress-initialize:2.4.0-20201102
    depends_on:
      - mysql
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/leaflet-map
      - ./docker-initialize.sh:/app/initialize.sh
      #-------------------------------------------------
      # Uncomment these along with the wordpress service
      # to debug themes and plugins
      #-------------------------------------------------
      - ./themes:/var/www/html/wp-content/themes
      # - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WP_PLUGINS: leaflet-map
      WORDPRESS_PORT: ${WP_PORT:-1234}
      WP_PORT: ${WP_PORT:-1234}
      WP_URL: ${WP_URL:-localhost:1234}
      WP_USER: admin
      WP_PASSWORD: password
      WP_THEME: twentynineteen

  wordpress:
    image: wordpress:5.5.3-php7.4
    depends_on:
      - cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/leaflet-map
      #-------------------------------------------------
      # Uncomment these along with the cli service
      # to debug themes and plugins
      #-------------------------------------------------
      - ./themes:/var/www/html/wp-content/themes
      # - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - ${WP_PORT:-1234}:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: rootpass

volumes:
  wp_db:
  wordpress:
